<<<<<<< HEAD
export const SET_SINGLE_DISCOURSE = 'SET_SINGLE_DISCOURSE';
export const SET_DISCOURSE_LIST = 'SET_DISCOURSE_LIST';

export const GET_DISCOURSE_LIST = 'GET_DISCOURSE_LIST';
export const GET_SINGLE_DISCOURSE = 'GET_SINGLE_DISCOURSE';


export default {
	SET_SINGLE_DISCOURSE,
	SET_DISCOURSE_LIST,
	GET_DISCOURSE_LIST,
	GET_SINGLE_DISCOURSE
=======
export const SET_SINGLE_DISCOURSE = 'SET_SINGLE_DISCOURSE'
export const SET_DISCOURSE_LIST = 'SET_DISCOURSE_LIST'

export const GET_DISCOURSE_LIST = 'GET_DISCOURSE_LIST'
export const GET_SINGLE_DISCOURSE = 'GET_SINGLE_DISCOURSE'

export default {
  SET_SINGLE_DISCOURSE,
  SET_DISCOURSE_LIST,
  GET_DISCOURSE_LIST,
  GET_SINGLE_DISCOURSE
>>>>>>> 729b8d1742a375601acf9c83c77d8addff2e0028
}
