const SET_SINGLE_DISCOURSE = 'SET_SINGLE_DISCOURSE';
const SET_DISCOURSE_LIST = 'SET_DISCOURSE_LIST';

const GET_DISCOURSE_LIST = 'GET_DISCOURSE_LIST';
const GET_SINGLE_DISCOURSE = 'GET_SINGLE_DISCOURSE';

export default {
	SET_SINGLE_DISCOURSE,
	SET_DISCOURSE_LIST,
	GET_DISCOURSE_LIST,
	GET_SINGLE_DISCOURSE
};
