const SET_SINGLE_ARTICLE = 'SET_SINGLE_ARTICLE';
const SET_ARTICLE_LIST = 'SET_ARTICLE_LIST';

const GET_ARTICLES = 'GET_ARTICLES';
const GET_SINGLE_ARTICLE = 'GET_SINGLE_ARTICLE';

export default {
	SET_SINGLE_ARTICLE,
	SET_ARTICLE_LIST,
	GET_ARTICLES,
	GET_SINGLE_ARTICLE
};
