const SET_SINGLE_ARTICLE = 'SET_SINGLE_ARTICLE';
const SET_MULTIPLE_ARTICLES = 'SET_MULTIPLE_ARTICLES';

const GET_ARTICLES = 'GET_ARTICLES';
const GET_SINGLE_ARTICLE = 'GET_SINGLE_ARTICLE'


export default {
	SET_SINGLE_ARTICLE,
	SET_MULTIPLE_ARTICLES,
	GET_ARTICLES,
	GET_SINGLE_ARTICLE
};
